# Generated by Django 5.1.6 on 2025-05-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On sale', 'On Sale'), ('Out of stock', 'Out Of Stock')], default='Available', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='merchstore.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON CART', 'On Cart'), ('TO PAY', 'To Pay'), ('TO SHIP', 'To Ship'), ('TO RECEIVE', 'To Receive'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.product')),
            ],
        ),
    ]
