# Generated by Django 5.1.6 on 2025-03-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_product_options_alter_producttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ImageURL',
            field=models.CharField(default=12, max_length=2000),
            preserve_default=False,
        ),
    ]
