# Generated by Django 5.1.6 on 2025-05-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
