# Generated by Django 5.1.6 on 2025-05-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_profile_bio_alter_job_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={},
        ),
    ]
