# Generated by Django 5.1.6 on 2025-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_article_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
