# Generated by Django 5.1.6 on 2025-03-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
